export { Home as HomeScreen } from './Home';
export { Ranks as RanksScreen } from './Ranks';
export { Message as MessageScreen } from './Message';
export { Account as AccountScreen } from './Account';
export { AddQuestion as AddQuestionScreen } from './AddQuestion';
export { Login as LoginScreen } from './Auth/Login';
export { Register as RegisterScreen } from './Auth/Register';
export { Classrooms as ClassroomsScreen } from './Classrooms';
export { ClassroomDetail as ClassroomDetailScreen } from './Classrooms/detail';
